<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "staffm"
 *
 * Auto generated by Extension Builder 2016-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = [
    'title' => 'Staffmanage',
    'description' => 'Employee database with qualifications, cost centers, companies and so on.',
    'category' => 'misc',
    'author' => 'Markus Puffer',
    'author_email' => 'm.puffer@pm-webdesign.eu',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '3.2.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
            'vhs' => '6.0.0-6.0.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];